import React from 'react';
import { X, Share2, Download, Gamepad2, Clock, Gauge, Thermometer, Cpu, CircuitBoard, Calendar, Zap } from 'lucide-react';
import { Share } from '@capacitor/share';
import { formatDuration, formatDate } from '../utils/sessionStorage';
import { t } from '../utils/i18n';

export default function ExportReport({ session, onClose }) {
    if (!session) return null;

    const handleShare = async () => {
        try {
            // Create text report
            const report = `
🎮 FrameForge - Performance Report
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📍 Game: ${session.gameName || 'Unknown'}
⏱️ Duration: ${formatDuration(session.duration)}
📅 Date: ${formatDate(session.savedAt)}

━━━━━━━━━━ FPS ━━━━━━━━━━
📊 Average: ${Math.round(session.avgFps)} FPS
📈 Maximum: ${Math.round(session.maxFps)} FPS
📉 Minimum: ${Math.round(session.minFps)} FPS

━━━━━━━━ TEMPS ━━━━━━━━
🔥 CPU Max: ${Math.round(session.maxCpuTemp)}°C
🌡️ GPU Max: ${Math.round(session.maxGpuTemp)}°C

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by FrameForge
            `.trim();

            await Share.share({
                title: `FrameForge - ${session.gameName}`,
                text: report,
                dialogTitle: t('share_report') || 'Compartilhar Relatório'
            });
        } catch (e) {
            console.error('Share error:', e);
            // Fallback to clipboard
            try {
                await navigator.clipboard.writeText(report);
                alert(t('copied_to_clipboard') || 'Copiado para área de transferência!');
            } catch (clipError) {
                console.error('Clipboard error:', clipError);
            }
        }
    };

    const getFpsColor = (fps) => {
        if (fps >= 60) return 'text-green-400';
        if (fps >= 30) return 'text-yellow-400';
        return 'text-red-400';
    };

    const getTempColor = (temp) => {
        if (temp >= 85) return 'text-red-400';
        if (temp >= 75) return 'text-orange-400';
        return 'text-green-400';
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
            <div className="bg-gray-900 border border-gray-800 rounded-2xl max-w-md w-full overflow-hidden">
                {/* Header */}
                <div className="flex items-center justify-between p-6 border-b border-gray-800 bg-gradient-to-r from-blue-600/20 to-purple-600/20">
                    <div className="flex items-center gap-3">
                        <Share2 className="w-6 h-6 text-blue-400" />
                        <h2 className="text-xl font-bold text-white">{t('performance_report') || 'Relatório'}</h2>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-gray-800 rounded-lg transition-colors">
                        <X className="w-5 h-5 text-gray-400" />
                    </button>
                </div>

                {/* Report Content */}
                <div className="p-6 space-y-4">
                    {/* Game Info */}
                    <div className="text-center pb-4 border-b border-gray-800">
                        <div className="flex items-center justify-center gap-2 mb-2">
                            <Gamepad2 className="w-5 h-5 text-green-400" />
                            <span className="text-xl font-bold text-white">{session.gameName || 'Unknown Game'}</span>
                        </div>
                        <div className="flex items-center justify-center gap-4 text-sm text-gray-500">
                            <span className="flex items-center gap-1">
                                <Clock className="w-3 h-3" />
                                {formatDuration(session.duration)}
                            </span>
                            <span className="flex items-center gap-1">
                                <Calendar className="w-3 h-3" />
                                {formatDate(session.savedAt)}
                            </span>
                        </div>
                    </div>

                    {/* FPS Stats */}
                    <div className="bg-gray-800/50 rounded-xl p-4">
                        <div className="flex items-center gap-2 mb-3">
                            <Gauge className="w-5 h-5 text-green-400" />
                            <span className="font-bold text-white">FPS</span>
                        </div>
                        <div className="grid grid-cols-3 gap-3 text-center">
                            <div className="bg-black/30 rounded-lg p-3">
                                <span className="block text-xs text-gray-500 mb-1">{t('minimum') || 'Mínimo'}</span>
                                <span className={`text-2xl font-bold ${getFpsColor(session.minFps)}`}>{Math.round(session.minFps)}</span>
                            </div>
                            <div className="bg-black/30 rounded-lg p-3 border border-green-500/30">
                                <span className="block text-xs text-gray-500 mb-1">{t('average') || 'Média'}</span>
                                <span className={`text-2xl font-bold ${getFpsColor(session.avgFps)}`}>{Math.round(session.avgFps)}</span>
                            </div>
                            <div className="bg-black/30 rounded-lg p-3">
                                <span className="block text-xs text-gray-500 mb-1">{t('maximum') || 'Máximo'}</span>
                                <span className={`text-2xl font-bold ${getFpsColor(session.maxFps)}`}>{Math.round(session.maxFps)}</span>
                            </div>
                        </div>
                    </div>

                    {/* Temperature Stats */}
                    <div className="grid grid-cols-2 gap-3">
                        {/* CPU */}
                        <div className="bg-gray-800/50 rounded-xl p-4">
                            <div className="flex items-center gap-2 mb-2">
                                <Cpu className="w-4 h-4 text-orange-400" />
                                <span className="text-sm font-medium text-gray-400">CPU</span>
                            </div>
                            <div className="flex items-baseline gap-1">
                                <span className={`text-3xl font-bold ${getTempColor(session.maxCpuTemp)}`}>{Math.round(session.maxCpuTemp)}</span>
                                <span className="text-gray-500">°C max</span>
                            </div>
                            <span className="text-xs text-gray-600">avg: {Math.round(session.avgCpuTemp)}°C</span>
                        </div>

                        {/* GPU */}
                        <div className="bg-gray-800/50 rounded-xl p-4">
                            <div className="flex items-center gap-2 mb-2">
                                <CircuitBoard className="w-4 h-4 text-green-400" />
                                <span className="text-sm font-medium text-gray-400">GPU</span>
                            </div>
                            <div className="flex items-baseline gap-1">
                                <span className={`text-3xl font-bold ${getTempColor(session.maxGpuTemp)}`}>{Math.round(session.maxGpuTemp)}</span>
                                <span className="text-gray-500">°C max</span>
                            </div>
                            <span className="text-xs text-gray-600">avg: {Math.round(session.avgGpuTemp)}°C</span>
                        </div>
                    </div>
                </div>

                {/* Share Button */}
                <div className="p-6 border-t border-gray-800">
                    <button
                        onClick={handleShare}
                        className="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 rounded-xl font-bold text-white transition-all flex items-center justify-center gap-3"
                    >
                        <Share2 className="w-5 h-5" />
                        {t('share_report') || 'Compartilhar Relatório'}
                    </button>
                </div>
            </div>
        </div>
    );
}
